"""empty message

Revision ID: 489ba3768f99
Revises: 698dd48326f9
Create Date: 2021-05-02 16:46:55.821632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489ba3768f99'
down_revision = '698dd48326f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'roles', ['name'])
    op.create_unique_constraint(None, 'roles', ['permission'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    # ### end Alembic commands ###
