"""empty message

Revision ID: 4b75e0931950
Revises: 6c63da6f800d
Create Date: 2021-05-01 03:36:57.055727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b75e0931950'
down_revision = '6c63da6f800d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('receiver', sa.Integer(), nullable=False))
    op.drop_constraint('transactions_reciver_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['receiver'], ['id'])
    op.drop_column('transactions', 'reciver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reciver', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_reciver_fkey', 'transactions', 'users', ['reciver'], ['id'])
    op.drop_column('transactions', 'receiver')
    # ### end Alembic commands ###
