"""empty message

Revision ID: 5488d8903dd7
Revises: 6ee94eeb9c36
Create Date: 2021-05-01 13:56:55.767799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5488d8903dd7'
down_revision = '6ee94eeb9c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_sender_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_receiver_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['receiver'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'wallets', ['sender'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_receiver_fkey', 'transactions', 'wallets', ['receiver'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_sender_fkey', 'transactions', 'wallets', ['sender'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
