"""empty message

Revision ID: 698dd48326f9
Revises: cea4cced3eec
Create Date: 2021-05-01 17:18:05.499525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698dd48326f9'
down_revision = 'cea4cced3eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'receiver',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'sender',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'sender',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'receiver',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
