"""empty message

Revision ID: 6c63da6f800d
Revises: 92d62cdcac8e
Create Date: 2021-05-01 03:23:53.739923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c63da6f800d'
down_revision = '92d62cdcac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_wallet_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['id'], ondelete='cascade')
    op.drop_constraint('wallets_user_id_fkey', 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key('wallets_user_id_fkey', 'wallets', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_wallet_id_fkey', 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###
