"""empty message

Revision ID: 92d62cdcac8e
Revises: abd61bd0d94d
Create Date: 2021-05-01 00:45:30.790213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d62cdcac8e'
down_revision = 'abd61bd0d94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('wallet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'wallet_id')
    # ### end Alembic commands ###
