"""empty message

Revision ID: cea4cced3eec
Revises: 5488d8903dd7
Create Date: 2021-05-01 14:05:53.759762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea4cced3eec'
down_revision = '5488d8903dd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'at')
    # ### end Alembic commands ###
